name: copilot-deploy-infra-pipeline

on:
  workflow_dispatch:       
  push:
    branches: ["main"]
    paths: 
      - 'scripts/deploy/**/*.bicep'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:

  integration:
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: integration
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}
      AZURE_OPENAI_EMBED_ENDPOINT: ${{secrets.AZURE_OPENAI_EMBED_ENDPOINT}}

# SMOKE TESTS SHOULD BE ADDED HERE

  production:
    needs: [integration]
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: production
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_OPENAI_ENDPOINT: ${{secrets.AZURE_OPENAI_ENDPOINT}}
      AZURE_OPENAI_EMBED_ENDPOINT: ${{secrets.AZURE_OPENAI_EMBED_ENDPOINT}}
